/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSearchImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryImport } from './routes/_authenticated/library'
import { Route as AuthenticatedBrowseImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated/admin'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUserSettingsRouteImport } from './routes/_authenticated/user-settings/route'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUserSettingsIndexImport } from './routes/_authenticated/user-settings/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedAdminIndexImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUserSettingsPreferencesImport } from './routes/_authenticated/user-settings/preferences'
import { Route as AuthenticatedUserSettingsAudioImport } from './routes/_authenticated/user-settings/audio'
import { Route as AuthenticatedSettingsPreferencesImport } from './routes/_authenticated/settings/preferences'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAudioImport } from './routes/_authenticated/settings/audio'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedLibraryHistoryImport } from './routes/_authenticated/library/history'
import { Route as AuthenticatedLibraryFollowingImport } from './routes/_authenticated/library/following'
import { Route as AuthenticatedLibraryFavoritesImport } from './routes/_authenticated/library/favorites'
import { Route as AuthenticatedAdminUsersImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStationsImport } from './routes/_authenticated/admin/stations'
import { Route as AuthenticatedAdminAnalyticsImport } from './routes/_authenticated/admin/analytics'

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSearchRoute = AuthenticatedSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedLibraryRoute = AuthenticatedLibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedBrowseRoute = AuthenticatedBrowseImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUserSettingsRouteRoute =
  AuthenticatedUserSettingsRouteImport.update({
    id: '/user-settings',
    path: '/user-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedUserSettingsIndexRoute =
  AuthenticatedUserSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUserSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedUserSettingsPreferencesRoute =
  AuthenticatedUserSettingsPreferencesImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedUserSettingsRouteRoute,
  } as any)

const AuthenticatedUserSettingsAudioRoute =
  AuthenticatedUserSettingsAudioImport.update({
    id: '/audio',
    path: '/audio',
    getParentRoute: () => AuthenticatedUserSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAudioRoute = AuthenticatedSettingsAudioImport.update(
  {
    id: '/audio',
    path: '/audio',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedLibraryHistoryRoute =
  AuthenticatedLibraryHistoryImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)

const AuthenticatedLibraryFollowingRoute =
  AuthenticatedLibraryFollowingImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)

const AuthenticatedLibraryFavoritesRoute =
  AuthenticatedLibraryFavoritesImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)

const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminStationsRoute = AuthenticatedAdminStationsImport.update(
  {
    id: '/stations',
    path: '/stations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any,
)

const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user-settings': {
      id: '/_authenticated/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof AuthenticatedUserSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/stations': {
      id: '/_authenticated/admin/stations'
      path: '/stations'
      fullPath: '/admin/stations'
      preLoaderRoute: typeof AuthenticatedAdminStationsImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/library/favorites': {
      id: '/_authenticated/library/favorites'
      path: '/favorites'
      fullPath: '/library/favorites'
      preLoaderRoute: typeof AuthenticatedLibraryFavoritesImport
      parentRoute: typeof AuthenticatedLibraryImport
    }
    '/_authenticated/library/following': {
      id: '/_authenticated/library/following'
      path: '/following'
      fullPath: '/library/following'
      preLoaderRoute: typeof AuthenticatedLibraryFollowingImport
      parentRoute: typeof AuthenticatedLibraryImport
    }
    '/_authenticated/library/history': {
      id: '/_authenticated/library/history'
      path: '/history'
      fullPath: '/library/history'
      preLoaderRoute: typeof AuthenticatedLibraryHistoryImport
      parentRoute: typeof AuthenticatedLibraryImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/audio': {
      id: '/_authenticated/settings/audio'
      path: '/audio'
      fullPath: '/settings/audio'
      preLoaderRoute: typeof AuthenticatedSettingsAudioImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/user-settings/audio': {
      id: '/_authenticated/user-settings/audio'
      path: '/audio'
      fullPath: '/user-settings/audio'
      preLoaderRoute: typeof AuthenticatedUserSettingsAudioImport
      parentRoute: typeof AuthenticatedUserSettingsRouteImport
    }
    '/_authenticated/user-settings/preferences': {
      id: '/_authenticated/user-settings/preferences'
      path: '/preferences'
      fullPath: '/user-settings/preferences'
      preLoaderRoute: typeof AuthenticatedUserSettingsPreferencesImport
      parentRoute: typeof AuthenticatedUserSettingsRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/user-settings/': {
      id: '/_authenticated/user-settings/'
      path: '/'
      fullPath: '/user-settings/'
      preLoaderRoute: typeof AuthenticatedUserSettingsIndexImport
      parentRoute: typeof AuthenticatedUserSettingsRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsAudioRoute: typeof AuthenticatedSettingsAudioRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsAudioRoute: AuthenticatedSettingsAudioRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPreferencesRoute:
      AuthenticatedSettingsPreferencesRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedUserSettingsRouteRouteChildren {
  AuthenticatedUserSettingsAudioRoute: typeof AuthenticatedUserSettingsAudioRoute
  AuthenticatedUserSettingsPreferencesRoute: typeof AuthenticatedUserSettingsPreferencesRoute
  AuthenticatedUserSettingsIndexRoute: typeof AuthenticatedUserSettingsIndexRoute
}

const AuthenticatedUserSettingsRouteRouteChildren: AuthenticatedUserSettingsRouteRouteChildren =
  {
    AuthenticatedUserSettingsAudioRoute: AuthenticatedUserSettingsAudioRoute,
    AuthenticatedUserSettingsPreferencesRoute:
      AuthenticatedUserSettingsPreferencesRoute,
    AuthenticatedUserSettingsIndexRoute: AuthenticatedUserSettingsIndexRoute,
  }

const AuthenticatedUserSettingsRouteRouteWithChildren =
  AuthenticatedUserSettingsRouteRoute._addFileChildren(
    AuthenticatedUserSettingsRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminStationsRoute: typeof AuthenticatedAdminStationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminStationsRoute: AuthenticatedAdminStationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryFavoritesRoute: typeof AuthenticatedLibraryFavoritesRoute
  AuthenticatedLibraryFollowingRoute: typeof AuthenticatedLibraryFollowingRoute
  AuthenticatedLibraryHistoryRoute: typeof AuthenticatedLibraryHistoryRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryFavoritesRoute: AuthenticatedLibraryFavoritesRoute,
  AuthenticatedLibraryFollowingRoute: AuthenticatedLibraryFollowingRoute,
  AuthenticatedLibraryHistoryRoute: AuthenticatedLibraryHistoryRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedUserSettingsRouteRoute: typeof AuthenticatedUserSettingsRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedUserSettingsRouteRoute:
    AuthenticatedUserSettingsRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/user-settings': typeof AuthenticatedUserSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/browse': typeof AuthenticatedBrowseRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/stations': typeof AuthenticatedAdminStationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/library/favorites': typeof AuthenticatedLibraryFavoritesRoute
  '/library/following': typeof AuthenticatedLibraryFollowingRoute
  '/library/history': typeof AuthenticatedLibraryHistoryRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/audio': typeof AuthenticatedSettingsAudioRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/user-settings/audio': typeof AuthenticatedUserSettingsAudioRoute
  '/user-settings/preferences': typeof AuthenticatedUserSettingsPreferencesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/user-settings/': typeof AuthenticatedUserSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}

export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/browse': typeof AuthenticatedBrowseRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/stations': typeof AuthenticatedAdminStationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/library/favorites': typeof AuthenticatedLibraryFavoritesRoute
  '/library/following': typeof AuthenticatedLibraryFollowingRoute
  '/library/history': typeof AuthenticatedLibraryHistoryRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/audio': typeof AuthenticatedSettingsAudioRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/user-settings/audio': typeof AuthenticatedUserSettingsAudioRoute
  '/user-settings/preferences': typeof AuthenticatedUserSettingsPreferencesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/user-settings': typeof AuthenticatedUserSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/user-settings': typeof AuthenticatedUserSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/stations': typeof AuthenticatedAdminStationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/library/favorites': typeof AuthenticatedLibraryFavoritesRoute
  '/_authenticated/library/following': typeof AuthenticatedLibraryFollowingRoute
  '/_authenticated/library/history': typeof AuthenticatedLibraryHistoryRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/audio': typeof AuthenticatedSettingsAudioRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/user-settings/audio': typeof AuthenticatedUserSettingsAudioRoute
  '/_authenticated/user-settings/preferences': typeof AuthenticatedUserSettingsPreferencesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/user-settings/': typeof AuthenticatedUserSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/settings'
    | '/user-settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin'
    | '/browse'
    | '/library'
    | '/profile'
    | '/search'
    | '/'
    | '/admin/analytics'
    | '/admin/stations'
    | '/admin/users'
    | '/library/favorites'
    | '/library/following'
    | '/library/history'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/user-settings/audio'
    | '/user-settings/preferences'
    | '/admin/'
    | '/settings/'
    | '/user-settings/'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/browse'
    | '/library'
    | '/profile'
    | '/search'
    | '/'
    | '/admin/analytics'
    | '/admin/stations'
    | '/admin/users'
    | '/library/favorites'
    | '/library/following'
    | '/library/history'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/audio'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/user-settings/audio'
    | '/user-settings/preferences'
    | '/admin'
    | '/settings'
    | '/user-settings'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/_authenticated/user-settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/stations'
    | '/_authenticated/admin/users'
    | '/_authenticated/library/favorites'
    | '/_authenticated/library/following'
    | '/_authenticated/library/history'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/audio'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/user-settings/audio'
    | '/_authenticated/user-settings/preferences'
    | '/_authenticated/admin/'
    | '/_authenticated/settings/'
    | '/_authenticated/user-settings/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/user-settings",
        "/_authenticated/admin",
        "/_authenticated/browse",
        "/_authenticated/library",
        "/_authenticated/profile",
        "/_authenticated/search",
        "/_authenticated/",
        "/_authenticated/users/"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/audio",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/preferences",
        "/_authenticated/settings/"
      ]
    },
    "/_authenticated/user-settings": {
      "filePath": "_authenticated/user-settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/user-settings/audio",
        "/_authenticated/user-settings/preferences",
        "/_authenticated/user-settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/analytics",
        "/_authenticated/admin/stations",
        "/_authenticated/admin/users",
        "/_authenticated/admin/"
      ]
    },
    "/_authenticated/browse": {
      "filePath": "_authenticated/browse.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/library": {
      "filePath": "_authenticated/library.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/library/favorites",
        "/_authenticated/library/following",
        "/_authenticated/library/history"
      ]
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/search": {
      "filePath": "_authenticated/search.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/analytics": {
      "filePath": "_authenticated/admin/analytics.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/stations": {
      "filePath": "_authenticated/admin/stations.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/admin/users": {
      "filePath": "_authenticated/admin/users.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/library/favorites": {
      "filePath": "_authenticated/library/favorites.tsx",
      "parent": "/_authenticated/library"
    },
    "/_authenticated/library/following": {
      "filePath": "_authenticated/library/following.tsx",
      "parent": "/_authenticated/library"
    },
    "/_authenticated/library/history": {
      "filePath": "_authenticated/library/history.tsx",
      "parent": "/_authenticated/library"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/audio": {
      "filePath": "_authenticated/settings/audio.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/preferences": {
      "filePath": "_authenticated/settings/preferences.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/user-settings/audio": {
      "filePath": "_authenticated/user-settings/audio.tsx",
      "parent": "/_authenticated/user-settings"
    },
    "/_authenticated/user-settings/preferences": {
      "filePath": "_authenticated/user-settings/preferences.tsx",
      "parent": "/_authenticated/user-settings"
    },
    "/_authenticated/admin/": {
      "filePath": "_authenticated/admin/index.tsx",
      "parent": "/_authenticated/admin"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/user-settings/": {
      "filePath": "_authenticated/user-settings/index.tsx",
      "parent": "/_authenticated/user-settings"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
